aws:
  accessKeyId: your-access-key-id
  secretAccessKey: your-secret-access-key
  s3:
    bucketName: your-bucket-name

valid:
  customer:
    tiers: free,pro,enterprise

spring:
  application:
    name: event-receiver-service

server:
  port: 8080
  
logging:
  level:
    root: INFO
    com.example.eventreceiver: DEBUG    
